# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip
    - name: Install dependencies
      run: |
        mkdir -p ~/.cache/pip
        pip install pip setuptools wheel --upgrade
        pip install -r requirements.txt --upgrade
        pip install -r test_requirements.txt --upgrade

    - name: flake8
      run: |
        flake8 calibpy

    - name: mypy 
      run: |
        mypy --ignore-missing-imports -p calibpy

    - name : pytest
      run: |
        pytest tests
  
